[build-system]
build-backend = 'mesonpy'
requires = ['meson-python', 'pybind11']

[project]
name = "apy_types"
version = "0.0.1"
authors = [
  { name="Example Author", email="author@example.com" }
]
description = "Python package for custom fixed-point and floating-point formats"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    #"License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

#[project.urls]
#Homepage = "https://github.com/pypa/sampleproject"
#Issues = "https://github.com/pypa/sampleproject/issues"

[tool.meson-python.args]
setup = ['--default-library=static']

[project.optional-dependencies]
doc = ["furo", "numpydoc", "sphinx", "sphinx_copybutton", "breathe"]
test = ["pytest"]