name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install -yy doxygen
    - name: Install APyTypes and doc dependencies
      run: |
        python -m pip install [.docs] -v
    - name: Run DoxyGen
      run:
         cd docs
         doxygen
         cd ..
    - id: deployment
      uses: sphinx-notes/pages@v3
